logging:
    level:
        org:
            hibernate:
                SQL: INFO
                type:
                    descriptor:
                        sql:
                            BasicBinder: INFO
            springframework:
                boot:
                    autoconfigure:
                        security: INFO
                security: INFO
server:
    metrics:
        export:
            graphite:
                step: 1s
    port: 6666

spring:
    servlet:
        multipart:
            maxFileSize: 6000KB
            maxRequestSize: 6000KB
    datasource:
        url: jdbc:mysql://172.17.0.1:3306/mustbusk
        username: mustbuskuser
        password: CJ17elaBsKEMUU4l
        testWhileIdle: trueq
        tomcat:
            max-active: 50
            max-idle: 20
            max-wait: 20000
            min-idle: 15
        validationQuery: SELECT 1
        driverClassName: com.mysql.jdbc.Driver
        initialization-mode: always
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
                id:
                    new_generator_mappings: false
        show-sql: false
    queries:
        roles-query: select u.email, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?
        users-query: select email, password, active from user where email=?

    site:
        name: 'https://www.mustbusk.com/'

---

spring:
    profiles: local
    thymeleaf:
        cache: false
    datasource:
        url: jdbc:mysql://127.0.0.1:3333/mustbusk
        username: mustbuskuser
        password: CJ17elaBsKEMUU4l
    site:
        name: 'http://localhost:8082/'

---

spring:
    profiles: test
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:mem:jpadb
        username: sa
        password:
        driverClassName: org.h2.Driver
    redis:
        host: 127.0.0.1
        database: 2
